name: TestNG Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LT_USERNAME: prakhargahlot
      LT_ACCESS_KEY: KSFyXiVoPkQ9xWSczVlR0BeL8Z6mU4oHvJWZXHgToD6hElruWN
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '1.8'

    - name: Build with Maven
      run: mvn -B clean install
    - name: Set LambdaTest credentials
      run: echo "LT_USERNAME=${LT_USERNAME}" >> $GITHUB_ENV && echo "LT_ACCESS_KEY=${LT_ACCESS_KEY}" >> $GITHUB_ENV

    - name: Run TestNG Tests
      run: mvn test -P android-single
